#ifndef APP_H
#define APP_H

#define PROJECT_NAME "@PROJECT_NAME@"

#define MAJOR_VERSION @MAJOR_VERSION@
#define MINOR_VERSION @MINOR_VERSION@
#define PATCH_VERSION @PATCH_VERSION@

#define AUTHOR_NAME "@AUTHOR_NAME@"
#define AUTHOR_EMAIL "@AUTHOR_EMAIL@"

#define PROJECT_LICENSE "@PROJECT_LICENSE@"

#endif
